# Generated by Django 2.2.2 on 2019-06-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('uid', models.IntegerField()),
                ('phone_number', models.CharField(max_length=11)),
                ('bought_date', models.DateField(auto_now=True)),
                ('used', models.BooleanField(default=False)),
                ('used_date', models.DateField()),
            ],
        ),
    ]
