# Generated by Django 2.2.2 on 2019-07-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190613_0922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='bought_date',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='used',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='used_date',
        ),
        migrations.AddField(
            model_name='ticket',
            name='checktime',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='number',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='password',
            field=models.BigIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='t1',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='t2',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='ypzt',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='phone_number',
            field=models.BigIntegerField(),
        ),
    ]
