# Generated by Django 2.2.2 on 2019-07-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190721_1215'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
    ]
