# Generated by Django 2.2.2 on 2019-07-21 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190721_1339'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ticket',
            table='api_ticket',
        ),
    ]
