# Generated by Django 2.2.2 on 2019-07-21 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190721_1341'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
    ]
