# Generated by Django 2.2.2 on 2019-07-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190721_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
